import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

const SUPABASE_URL = "https://chllzkgugwuerlnbltay.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_rpzSMoGHXVKEIRwipYmrHg_64fqgX0y";

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const tabLogin = document.getElementById("tabLogin");
const tabSignup = document.getElementById("tabSignup");
const loginPanel = document.getElementById("loginPanel");
const signupPanel = document.getElementById("signupPanel");
const authMessage = document.getElementById("authMessage");
const sessionPanel = document.getElementById("sessionPanel");
const sessionSummary = document.getElementById("sessionSummary");
const adminPanel = document.getElementById("adminPanel");
const generatedCode = document.getElementById("generatedCode");

const loginButton = document.getElementById("loginButton");
const signupButton = document.getElementById("signupButton");
const logoutButton = document.getElementById("logoutButton");
const generateCodeButton = document.getElementById("generateCodeButton");

function setMessage(text, type = "") {
	authMessage.textContent = text || "";
	authMessage.classList.remove("is-ok", "is-warn", "is-error");
	if (type) {
		authMessage.classList.add(type);
	}
}

function setLoading(button, loading) {
	button.disabled = loading;
	button.textContent = loading ? "Working..." : button.dataset.defaultText;
}

function setIdentityStorage(user, role) {
	if (!user) return;
	const email = String(user.email || "").trim();
	const displayName = String((user.user_metadata && user.user_metadata.display_name) || "").trim();
	const fallbackName = email ? email.split("@")[0].replace(/[._-]+/g, " ").trim() : "";
	const accountName = displayName || fallbackName || "Member";

	try {
		window.localStorage.setItem("accountName", accountName);
		window.localStorage.setItem("accountEmail", email);
		window.localStorage.setItem("accountRole", role || "member");
		window.localStorage.setItem("accountUserId", user.id || "");
	} catch (err) {
		// Ignore storage failures to avoid blocking auth behavior.
	}
}

function clearIdentityStorage() {
	try {
		window.localStorage.removeItem("accountName");
		window.localStorage.removeItem("accountEmail");
		window.localStorage.removeItem("accountRole");
		window.localStorage.removeItem("accountUserId");
	} catch (err) {
		// Ignore storage failures to avoid blocking auth behavior.
	}
}

function normalizeCode(code) {
	return (code || "").trim().toUpperCase().replace(/\s+/g, "");
}

function isValidCodeFormat(code) {
	// Only allow the exact format generated by randomCode: two 4-char alphanum segments e.g. AB12-CD34
	return /^[A-Z2-9]{4}-[A-Z2-9]{4}$/.test(code);
}

function randomCode() {
	const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
	const segmentLength = 4;
	const segments = 2;
	const parts = [];

	for (let i = 0; i < segments; i += 1) {
		let chunk = "";
		for (let j = 0; j < segmentLength; j += 1) {
			chunk += alphabet[Math.floor(Math.random() * alphabet.length)];
		}
		parts.push(chunk);
	}

	return parts.join("-");
}

async function redeemAccessCode(code, uid) {
	const cleanCode = normalizeCode(code);
	if (!cleanCode) {
		throw new Error("Access code is required.");
	}

	if (!isValidCodeFormat(cleanCode)) {
		throw new Error("Invalid access code format.");
	}

	// Read the code first to give a clear error message
	const { data: codeRow, error: readError } = await supabase
		.from("access_codes")
		.select("status, redeemed_by")
		.eq("code", cleanCode)
		.maybeSingle();

	if (readError) throw readError;
	if (!codeRow) throw new Error("Access code not found.");
	if (codeRow.status !== "active") throw new Error("Access code is not active.");
	if (codeRow.redeemed_by) throw new Error("Access code has already been used.");

	// Mark the code as redeemed (conditional update — only succeeds if still active & unredeemed)
	const { error: updateError, count } = await supabase
		.from("access_codes")
		.update({ status: "used", redeemed_by: uid, redeemed_at: new Date().toISOString() })
		.eq("code", cleanCode)
		.eq("status", "active")
		.is("redeemed_by", null);

	if (updateError) throw updateError;
	if (count === 0) throw new Error("Access code has already been used.");

	return cleanCode;
}

function showTab(tabName) {
	const showLogin = tabName === "login";

	tabLogin.classList.toggle("is-active", showLogin);
	tabLogin.setAttribute("aria-selected", showLogin ? "true" : "false");

	tabSignup.classList.toggle("is-active", !showLogin);
	tabSignup.setAttribute("aria-selected", !showLogin ? "true" : "false");

	loginPanel.classList.toggle("is-hidden", !showLogin);
	loginPanel.hidden = !showLogin;
	signupPanel.classList.toggle("is-hidden", showLogin);
	signupPanel.hidden = showLogin;
}

async function updateSessionUi(user) {
	if (!user) {
		sessionPanel.classList.add("is-hidden");
		sessionPanel.hidden = true;
		adminPanel.classList.add("is-hidden");
		adminPanel.hidden = true;
		generatedCode.textContent = "";
		clearIdentityStorage();
		return;
	}

	const { data: userRow } = await supabase
		.from("users")
		.select("role")
		.eq("id", user.id)
		.maybeSingle();

	const role = userRow ? String(userRow.role || "") : "";
	const isAdmin = role === "admin";
	setIdentityStorage(user, role || "member");

	sessionSummary.textContent = `${user.email} is signed in${isAdmin ? " (admin)" : ""}.`;
	sessionPanel.classList.remove("is-hidden");
	sessionPanel.hidden = false;
	adminPanel.classList.toggle("is-hidden", !isAdmin);
	adminPanel.hidden = !isAdmin;
}

function toFriendlyError(err) {
	const message = err && err.message ? err.message : "Unknown error";
	if (message.includes("Invalid login credentials")) return "Invalid email or password.";
	if (message.includes("User already registered")) return "This email is already registered.";
	if (message.includes("Password should be")) return "Use a stronger password with at least 6 characters.";
	if (message.includes("auth/invalid-credential")) return "Invalid email or password.";
	if (message.includes("auth/email-already-in-use")) return "This email is already registered.";
	if (message.includes("auth/weak-password")) return "Use a stronger password with at least 8 characters.";
	return message;
}

tabLogin.addEventListener("click", () => {
	showTab("login");
	setMessage("");
});

tabSignup.addEventListener("click", () => {
	showTab("signup");
	setMessage("");
});

loginPanel.addEventListener("submit", async (event) => {
	event.preventDefault();
	const form = new FormData(loginPanel);
	const email = String(form.get("email") || "").trim();
	const password = String(form.get("password") || "");

	if (!email || !password) {
		setMessage("Email and password are required.", "is-warn");
		return;
	}

	try {
		setLoading(loginButton, true);
		const { error } = await supabase.auth.signInWithPassword({ email, password });
		if (error) throw error;
		setMessage("Logged in successfully.", "is-ok");
	} catch (err) {
		setMessage(toFriendlyError(err), "is-error");
	} finally {
		setLoading(loginButton, false);
	}
});

signupPanel.addEventListener("submit", async (event) => {
	event.preventDefault();
	const form = new FormData(signupPanel);
	const name = String(form.get("name") || "").trim();
	const email = String(form.get("email") || "").trim();
	const password = String(form.get("password") || "");
	const rawCode = String(form.get("accessCode") || "");

	if (!email || !password || !rawCode) {
		setMessage("Email, password, and access code are required.", "is-warn");
		return;
	}

	let createdUserId = null;
	try {
		setLoading(signupButton, true);
		const { data: signUpData, error: signUpError } = await supabase.auth.signUp({
			email,
			password,
			options: { data: { display_name: name } }
		});
		if (signUpError) throw signUpError;
		const createdUser = signUpData.user;
		createdUserId = createdUser.id;

		const code = await redeemAccessCode(rawCode, createdUserId);

		const { error: profileError } = await supabase.from("users").upsert({
			id: createdUserId,
			email: createdUser.email,
			display_name: name || "",
			role: "member",
			access_code: code,
			created_at: new Date().toISOString()
		});
		if (profileError) throw profileError;

		signupPanel.reset();
		setMessage("Account created. You are now signed in.", "is-ok");
	} catch (err) {
		// If signup partially failed, sign out to avoid a logged-in orphan session
		if (createdUserId) {
			await supabase.auth.signOut().catch(() => {});
		}
		setMessage(toFriendlyError(err), "is-error");
	} finally {
		setLoading(signupButton, false);
	}
});

logoutButton.addEventListener("click", async () => {
	try {
		await supabase.auth.signOut();
		clearIdentityStorage();
		setMessage("Logged out.", "is-ok");
	} catch (err) {
		setMessage(toFriendlyError(err), "is-error");
	}
});

if (new URLSearchParams(window.location.search).get("logout") === "1") {
	supabase.auth.signOut().catch(function () {
		// Ignore sign-out errors and still clear local identity cache.
	});
	clearIdentityStorage();
	setMessage("Logged out.", "is-ok");
}

generateCodeButton.addEventListener("click", async () => {
	const { data: { session } } = await supabase.auth.getSession();
	const user = session && session.user;
	if (!user) {
		setMessage("You must be logged in.", "is-warn");
		return;
	}

	try {
		setLoading(generateCodeButton, true);
		const { data: userRow } = await supabase
			.from("users")
			.select("role")
			.eq("id", user.id)
			.maybeSingle();

		const role = userRow ? String(userRow.role || "") : "";
		if (role !== "admin") {
			throw new Error("Only admin accounts can generate access codes.");
		}

		const code = randomCode();
		const { error } = await supabase.from("access_codes").insert({
			code,
			status: "active",
			created_by: user.id,
			created_by_email: user.email || "",
			created_at: new Date().toISOString(),
			redeemed_by: null,
			redeemed_at: null
		});
		if (error) throw error;

		generatedCode.textContent = code;
		setMessage("Access code generated.", "is-ok");
	} catch (err) {
		setMessage(toFriendlyError(err), "is-error");
	} finally {
		setLoading(generateCodeButton, false);
	}
});

[loginButton, signupButton, generateCodeButton].forEach((button) => {
	button.dataset.defaultText = button.textContent;
});

supabase.auth.onAuthStateChange(async (event, session) => {
	try {
		await updateSessionUi(session && session.user);
		if (session && session.user) {
			loginPanel.classList.add("is-hidden");
			loginPanel.hidden = true;
			signupPanel.classList.add("is-hidden");
			signupPanel.hidden = true;
			tabLogin.classList.remove("is-active");
			tabSignup.classList.remove("is-active");
		} else {
			showTab("login");
		}
	} catch (err) {
		setMessage(toFriendlyError(err), "is-error");
	}
});

// Check existing session on page load
supabase.auth.getSession().then(async ({ data: { session } }) => {
	try {
		await updateSessionUi(session && session.user);
		if (session && session.user) {
			loginPanel.classList.add("is-hidden");
			loginPanel.hidden = true;
			signupPanel.classList.add("is-hidden");
			signupPanel.hidden = true;
			tabLogin.classList.remove("is-active");
			tabSignup.classList.remove("is-active");
		} else {
			showTab("login");
		}
	} catch (err) {
		setMessage(toFriendlyError(err), "is-error");
	}
});

showTab("login");
